---
apiVersion: v1
kind: Service
metadata:
  name: butterfly
  labels:
    app: butterfly
spec:
  ports:
    - port: 10080
  selector:
    app: butterfly
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: butterfly
  labels:
    app: butterfly
spec:
  selector:
    matchLabels:
      app: butterfly
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: butterfly
        tier: frontend
    spec:
      containers:
      - image: quay.io/openshifthomeroom/workshop-terminal
        name: butterfly
        env:
        - name: OC_VERSION
          value: 3.11.161
        ports:
        - containerPort: 10080
          name: butterfly
