---
- name: Create butterfly project for each user
  k8s:
    verify_ssl: "{{ verify_ssl }}"
    name: "ocwt-user{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  loop: "{{ query('sequence', 'start=1 end={{ generic_count }}') }}"
  loop_control:
    pause: "{{ generic_pause }}"

- name: Deploy terminal application
  k8s:
    namespace: "{{ 'ocwt-user%x' | format(item) }}"
    state: present
    verify_ssl: "{{ verify_ssl }}"
    definition: "{{ lookup('file', 'files/butterfly.yaml') }}"
  loop: "{{ range(1, generic_count + 1, 1)|list }}"
  loop_control:
    pause: "{{ generic_pause }}"

- name: Create a Route object from an inline definition
  k8s:
    state: present
    verify_ssl: "{{ verify_ssl }}"
    namespace: "{{ 'ocwt-user%x' | format(item) }}"
    definition:
      apiVersion: v1
      kind: Route
      metadata:
        name: butterfly
      spec:
        to:
          kind: Service
          name: butterfly
  loop: "{{ range(1, generic_count + 1, 1)|list }}"
  loop_control:
    pause: "{{ generic_pause }}"
